apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
  ports:
    - name: http2
      port: 80
      nodePort: 31380
      targetPort: 8080
    - name: https
      port: 443
      nodePort: 31390
      targetPort: 8443
