apiVersion: v1
kind: Service
metadata:
  name: k8s-sample-app-service
  namespace: cloud-testing-env
spec:
  selector:
    app: k8s-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

