
openapi: 3.0.1
info:
  title: Wixstage Demo API
  description: A simple Wixstage API
  version: "1.0"
servers:
- url: http://k8s-sample-app.wewix.net
- url: http://localhost:8000
tags:
- name: api
  description: Main operations
paths:
  /api/cube/{num}:
    get:
      tags:
      - api
      operationId: get_cube
      parameters:
      - name: num
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content: {}
  /api/fibonacci/{n}:
    get:
      tags:
      - api
      operationId: get_fibonacci
      parameters:
      - name: "n"
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content: {}
  /api/hello:
    get:
      tags:
      - api
      operationId: get_hello_world
      responses:
        "200":
          description: Success
          content: {}
  /api/square/{num}:
    get:
      tags:
      - api
      operationId: get_square
      parameters:
      - name: num
        in: path
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content: {}
components:
  responses:
    ParseError:
      description: When a mask can't be parsed
      content: {}
    MaskError:
      description: When any error occurs on mask
      content: {}
x-original-swagger-version: "2.0"