apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: k8s-sample-app
  description: K8S Sample App
  annotations:
    backstage.io/kubernetes-id: k8s-sample-app
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - flask
  links:
    - url: https://systemit-k8s-sample-app.wewix.net/api
      title: Sample app
      icon: dashboard
      type: service
    - url: https://systemit-jaeger.wewix.net/search?service=k8s-sample-app
      title: Jaeger Tracing
      icon: AcUnit
      type: metrics-dashboard
    - url: https://systemit-kiali.wewix.net/kiali/console/namespaces/cloud-testing-env/workloads/k8s-sample-app-deployment
      title: Kiali Logs
      icon: dashboard
      type: logs-dashboard  
spec:
  type: service
  lifecycle: production
  owner: guests:pavelza
  system: Wixstage
  providesApis:
  - k8s-sample-app-api
