apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-test-app-deployment
  namespace: cloud-testing-env
  labels:
    app: jaeger-test-app
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-test-app
  template:
    metadata:
      labels:
        app: jaeger-test-app
    spec:
      containers:
        - name: k8s-sample-app
          image: docker.io/pavelzagalsky/jaeger-test-app:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 81
          resources:
            requests:
              memory: "16Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
