apiVersion: v1
kind: Service
metadata:
  labels:
    app: jaeger-test-app
  name: jaeger-test-app-service
  namespace: cloud-testing-env
spec:
  selector:
    app: jaeger-test-app
  type: NodePort
  ports:
  - port: 81
    targetPort: 81
