name: Manual Build Multi-Arch Docker Image
on: 
    workflow_dispatch:
        inputs:
            tag:
                required: true
                description: tag name
                default: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract the image name and tag
        run: |
          echo "REPO_TAG=pavelzagalsky/k8s-sample-app:${{ inputs.tag}}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./app/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.REPO_TAG }}